### ISSUE TITLE
Book Pg-7   : Not clear at all what to do

### ISSUE THREAD

**Issue by keithn** [demystifyfp/FsTweet#1]
Basically the command line instructions are broken, you can't run them as is and get the project working as described.  The book even makes note that future versions are not compatible but doesn't say what to do instead.

Am I now supposed to try and work out what I need to do with tools I haven't worked with before?

**Comment by eqr** [comment]
Frankly speaking, I've found the whole thing around DotLiquid and Suave seriously broken. Spent two days trying to match the version of Suave.DotLiquid and Liquid, it compiles at some history points and with the latest beta but does not work with mysterious errors with cryptic type names (hello F#). I decided to wait until Suave.DotLiquid 2.3.0 is done and then try again.

**Comment by demystifyfp** [comment]
Hi @keithn, 

The command line instructions in the book will work only in bash and not in Powershell or DOS prompt. 

In windows, you can either use the [Ubuntu Bash](https://www.howtogeek.com/265900/everything-you-can-do-with-windows-10s-new-bash-shell/) or [git bash](http://www.techoism.com/how-to-install-git-bash-on-windows/)

As mentioned in the book, instead of using Forge, you can use an IDE (either Visual Studio or Rider) for managing files and project. I choose Forge, to do things agnostic of any IDEs but unfortunately, it was updated without backward compatibility and my bad I missed the instructions to install the lower version of it in the book. (Will address it sooner)

You can download the version 1.4.2 of Forge from [here](https://github.com/fsharp-editing/Forge/releases/tag/1.4.2), extract the zip file and Add Forge location to your PATH environment variable. After doing this, you can use "Forge" from the bash.

**Comment by demystifyfp** [comment]
Hi @eqr, I felt the name when I was working on it. As described in the book, if you install DotLiquid Nuget package with version **2.0.64** and then installing Suave.DotLiquid works.

**Comment by demystifyfp** [comment]
@keithn Just now noticed that the Suave template in the Forge has also updated to use .NET core and the new template is not compatible with the older version. Started working on editing the first chapter of the book on how to work around this incompatibilities and I will push the update as soon as it is done.

**Comment by demystifyfp** [comment]
Thanks, @keithn & @eqr for reporting the issue. I've fixed both the issues in the latest update.
